### ISSUE TITLE
Locks Are Not Being Picked Up By Schematics or Structure Blocks

### ISSUE THREAD

**Issue by Boolyman** [Melonslise/Locks#15] opened 2019-07-15 21:54 UTC
I REALLY love your mod, it is the first one that has done exactly the things I need it to as far as locking and unlocking blocks.  My upcoming modpack has structures that spawn which will have buttons inside that must be unlocked before the player can progress.  Unfortunately, for some reason your locks are not being picked up by the Schematic or Strucutre capture functions,. which are how I copy the structures to each world.  I really hope there is something you can do to help me find out why they aren't being captured.  Are the locks coded in a certain way that is not scanned properly?

**Comment by MercurialPony** [comment] 2019-07-15 22:50
Locks are only generated on chests during world creation for now

**Comment by MercurialPony** [comment] 2019-07-15 22:50
Duplicate of #5

**Comment by Boolyman** [comment] 2019-07-15 23:12
I see the other ticket has been open since March.  Is there anything I can do to help with this process moving forward?  Paypal donation or something?

**Comment by MercurialPony** [comment] 2019-07-15 23:16
Oh no, no. I’ll get it done at some point. Probably before summer ends

**Comment by MercurialPony** [comment] 2020-03-19 22:18
Managed to get it to work! Wait for the next update

**Closed as completed** 2020-07-20 21:28 UTC
Labels: duplicate, enhancement
