### ISSUE TITLE
[1.12.2] Lockable Blocks config option not persisting after world reload

### ISSUE THREAD

**Issue by Lucky-Red** [Melonslise/Locks#44] opened 2020-07-22 23:54 UTC
After adding modded blocks to the list of lockable blocks in the config, everything works as intended. However, upon exiting and re-entering the world, the same modded blocks can no longer be locked. The CUI still appears, and the sound of a lock clicking into place can be heard, but no lock is actually applied to the block.

**Comment by MercurialPony** [comment] 2020-07-23 08:05
I could not reproduce this bug on my own. Do you have a dedicated server or is this in a singleplayer world?

**Comment by Lucky-Red** [comment] 2020-07-23 09:10
This was with a singleplayer world in a custom modpack (Forge version 14.23.5.2854). I've attached my edited config file in case it's an issue with my syntax.

[locks.txt](https://github.com/Melonslise/Locks/files/4964879/locks.txt)

**Comment by MercurialPony** [comment] 2020-07-23 09:13
It looks correct. I checked with quark too myself and I did not see this issue at all. However, I did add "quark:.*chest" into my config unlike your "quark:custom_chest". Can you send me the full mod list so I can check myself?

**Comment by Lucky-Red** [comment] 2020-07-23 09:22
[modlist.txt](https://github.com/Melonslise/Locks/files/4964933/modlist.txt)
Here's the full modlist.

**Comment by MercurialPony** [comment] 2020-07-23 09:27
Do you have a download link/page for your modpack? Not sure I want to download all those by hand

**Comment by Lucky-Red** [comment] 2020-07-23 09:39
I've managed to reproduce the issue using a modpack consisting of only the Locks mod and Iron Chests (just as a test for modded blocks), leading me to believe that it's something to do with the config itself. Also worth noting is that prior to the config's compatibility with regex wildcards, my list of added lockable blocks was much longer. Launching the updated version of the mod with the full list (as opposed to the current one that uses wildcards) resulted in a fatal exception any time I tried to join a world.

**Comment by MercurialPony** [comment] 2020-07-23 09:55
I have just tried with iron chests and I just cannot reproduce the issue. My steps were:
1. create a new world
2. place 2 iron chests down
3. add "ironchest:.*chest" to the config from the mod options menu (esc->mod options->locks->config)
4. add a lock onto one of the chests
5. quit world
6. re enter world and add lock onto the second chest

I did not run into the issue you described at all. Also please, show me the crash log with your old config, that might be some other issue

**Comment by Lucky-Red** [comment] 2020-07-23 10:01
Interestingly, the issue does not happen when the config only contains the entries for vanilla minecraft blocks and those from Iron Chests, but does occur if I use the config file uploaded earlier.
As requested, here is a log of the exception encountered with my longer, original config file that does not make use of regex wildcards.
[latest.txt](https://github.com/Melonslise/Locks/files/4965154/latest.txt)

**Comment by MercurialPony** [comment] 2020-07-23 10:08
And you never got this kind of issue in 2.3?

**Comment by Lucky-Red** [comment] 2020-07-23 10:09
That's correct. The only bugs I experienced in 2.3 were the now-fixed issues of locks appearing transparent, and keys disappearing from keyrings.

**Comment by MercurialPony** [comment] 2020-07-23 10:20
Alright, I've been able to reproduce the bug by using your exact config. Now I should be able to see why it's happening

**Comment by MercurialPony** [comment] 2020-07-23 15:29
Should be fixed now. Will push new version 2.5 to curse in just a few minutes. Reopen this issue if it persists

**Closed as completed by MercurialPony** 2020-07-23 15:29 UTC
