### ISSUE TITLE
Keyring deletes keys when placed in offhand in MP

### ISSUE THREAD

**Issue by Loriborn** [Melonslise/Locks#8] opened 2019-05-12 02:11 UTC
Related to #4 , placing the key ring in the offhand slot in a multiplayer game with this mod alone results in the keyring emptying, and unlike #4 , this deletes the keys, rather than just visually removing them. The keyring container seems to not be networked completely.

**Comment by Loriborn** [comment] 2019-05-26 00:09
Any progress on this issue?

**Comment by Melonslise** [comment] 2019-05-26 07:28
Duplicate of #4

**Comment by Melonslise** [comment] 2019-05-26 07:30
No, I’m currently busy with exams and whatnot. I’ll get to work during the summer.

**Comment by Melonslise** [comment] 2019-05-26 07:33
Duplicate of #4

**Closed** 2019-06-14 22:10 UTC
Labels: bug
